### ISSUE TITLE
[Feature] Full localization (built-in boilerplate, decorators, etc)

### ISSUE THREAD

**Issue by barthofu** [barthofu/tscord#11]
Atm, not all built-in commands and guards are localized.

**Comment by barthofu** [comment]
Solution for `nameLocalizations` and `descriptionLocalizations`:
- [ ] An utility which extracts the current logic implemented by @Mr-Artemus 
- [ ] An additional and optional field `localizationSource` which will permit the `@Slash` to retrieve the potential values for the `nameLocalizations` and `descriptionLocalizations`. 
   e.g: 
   ```ts
   @Slash({
      name: 'help',
      localizationSource: 'HELP'
   })
   ```
- [ ] Automatically tries to get the standardized localization source (e.g: `COMMANDS.<COMMAND_NAME>.<NAME|DESCRIPTION>`) from the command file name

**Comment by barthofu** [comment]
## Todo
- [ ] Replicate this logic for the `@SlashOption` decorator (and maybe others)
